spring.application.name=docker-demo

spring.datasource.url=jdbc:postgresql://mon-postgres:5432/mabase
spring.datasource.username=postgres
spring.datasource.password=monmotdepasse
spring.jpa.hibernate.ddl-auto=update